version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017
clone_folder: c:\projects\xenos

platform: 
  - Win32
  - x64

configuration: 
  - Debug
  - Release
  
install:
  - cmd: git submodule update --init --recursive
 
build:
  parallel: true
  project: Xenos.sln