version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017
clone_folder: c:\projects\blackbone

platform: 
  - Win32
  - x64

configuration: 
  - Debug
  - Debug(DLL)
  - Release
  - Release(DLL)
  
build:
  parallel: true
  project: BlackBone.sln 

skip_commits:
  message: /Driver/